package com.quantitymeasurement.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

/**
 * 
 * JwtAuthenticationFilter forms the most paramount architectural component 
 * distinguishing Stateless APIs from conventional heavy Form Login Spring mechanisms.
 * 
 * <p>
 * It extends `OncePerRequestFilter` to unilaterally guarantee execution happens 
 * uniformly precisely one time per incoming independent HTTP Request pipeline structure.
 * </p>
 * 
 * <p>
 * Fundamental Operations Overview:
 * 1. Scrutinize all inbound network requests for standard "Authorization" Header metadata.
 * 2. Specifically extract token content appearing after default "Bearer " HTTP standards suffix.
 * 3. Leverage the injected JwtUtil instance properly identifying the underlying authenticating username.
 * 4. Pass validated identity over immediately directly querying CustomUserDetailsService components.
 * 5. Update application thread-local `SecurityContextHolder` establishing context statefully.
 * </p>
 */
@Component
public class JwtAuthenticationFilter extends OncePerRequestFilter {

    private final JwtUtil jwtUtil;
    private final CustomUserDetailsService customUserDetailsService;

    /**
     * Dependency injected constructor establishing necessary component integrations.
     * 
     * @param jwtUtil The primary engine responsible for decoding parsing implementations.
     * @param customUserDetailsService Database integration component establishing user retrieval functionality.
     */
    @Autowired
    public JwtAuthenticationFilter(JwtUtil jwtUtil, CustomUserDetailsService customUserDetailsService) {
        this.jwtUtil = jwtUtil;
        this.customUserDetailsService = customUserDetailsService;
    }

    /**
     * Internal implementation executed seamlessly upon inbound architectural traversal flows.
     * 
     * <p>
     * Every individual HTTP request traverses sequentially through this method. If proper 
     * Security structures map equivalently against known variables, Authentication 
     * context receives automatic propagation seamlessly continuing onward down the Chain.
     * </p>
     * 
     * @param request The complete underlying raw HTTP context generated by frontend consumer systems.
     * @param response The standard response interface where data writes ultimately formulate outgoing streams.
     * @param filterChain Architecture pipeline directing logic cascading subsequent next filter implementations.
     * @throws ServletException Generally thrown when underlying HTTP structures fail resolving internal state variables.
     * @throws IOException I/O anomalies surfacing upon manipulating stream buffering interfaces directly.
     */
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {

        // Isolate requested default Standard 'Authorization' HTTP Request contextual Headers.
        final String authorizationHeader = request.getHeader("Authorization");

        String username = null;
        String jwtToken = null;

        /**
         * Confirm immediately existence alongside expected structural "Bearer " prefixes.
         * The standard configuration inherently attaches token content starting identically at index position number 7.
         */
        if (authorizationHeader != null && authorizationHeader.startsWith("Bearer ")) {
            jwtToken = authorizationHeader.substring(7); // Removes textual prefix cleanly isolating token string structure

            try {
                // Extracts subject from token mapping internally to username identity.
                username = jwtUtil.extractUsername(jwtToken);
            } catch (Exception e) {
                // If any error occurs internally reading structure we safely ignore updating the Security Context.
                logger.error("Exception parsing or extracting Username string dynamically: {}", e);
            }
        }

        /**
         * Validates successfully extracted identity string logic ensuring no existing authenticated structures 
         * are concurrently active overriding previous requests dynamically.
         */
        if (username != null && SecurityContextHolder.getContext().getAuthentication() == null) {

            // Initiate comprehensive database loading strategy confirming user active integrity functionality
            UserDetails userDetails = this.customUserDetailsService.loadUserByUsername(username);

            // Invoke token comprehensive validation confirming timing structures alongside equivalent user associations.
            if (jwtUtil.validateToken(jwtToken, userDetails)) {

                // Dynamically establish full Authentication Context Token leveraging loaded Authorities architecture interfaces
                UsernamePasswordAuthenticationToken authenticationToken = new UsernamePasswordAuthenticationToken(
                        userDetails, null, userDetails.getAuthorities());

                // Overlay specific request origin network structure mapping details integrating dynamically.
                authenticationToken.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));

                // Finalize architectural traversal by cementing completely established Authentication variable into Holder
                SecurityContextHolder.getContext().setAuthentication(authenticationToken);
            }
        }

        // Continues forwarding raw underlying request structure to whatever Spring Security next defines filter wise.
        filterChain.doFilter(request, response);
    }
}
