# Server configuration
server.port=8080

# === UC17: MySQL Database Connectivity ===
# Automatically generates the database if it is missing using createDatabaseIfNotExist
spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Auto-DDL
# 'update' automatically generates and modifies your MySQL table columns to match Entity classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect